### ISSUE TITLE
[ Common ] FMVs black levels are wrong when HDR is on

### ISSUE THREAD

**Issue by N8endo** [julianxhokaxhiu/FFNx#499]
When HDR is enabled in Windows, FMVs and static backgrounds like the background of the promise on the well scene display incorrect black levels.  There are crushed blacks and a lot of posterization.  When HDR is disabled the game seems to display everything fine.

- Nvidia RTX 3080
- Driver Version 516.94

SDR
![SDR1](https://user-images.githubusercontent.com/17175005/190964079-6bf9f6cd-94ab-4543-8b90-415a182188dc.png)

HDR
![HDR1](https://user-images.githubusercontent.com/17175005/190964096-a37f62f5-bba9-4c27-82da-4ed027915592.png)

SDR
![SDR2](https://user-images.githubusercontent.com/17175005/190964103-cbabcb16-d589-4c05-9a5b-bedcf5bcc091.png)

HDR
![HDR2](https://user-images.githubusercontent.com/17175005/190964110-f5ccb866-1367-4266-a685-d21700cef37e.png)

SDR
![SDR3](https://user-images.githubusercontent.com/17175005/190964119-97e3a5ee-2b42-4db1-ba84-3ba14cdddfcc.png)

HDR
![HDR3](https://user-images.githubusercontent.com/17175005/190964126-45a19884-3386-4b17-af6c-f38e6333f046.png)

**Comment by julianxhokaxhiu** [comment]
Please provide some screenshots.

**Comment by natepley** [comment]
> Please provide some screenshots.

Screenshots provided.  Notice the really bad posterization in the HDR screenshots compared to the smooth gradients in the SDR pictures.

**Comment by julianxhokaxhiu** [comment]
Did you try the latest FFNx canary before posting the screenshots?

**Comment by natepley** [comment]
I was on 1.13.0.82

**Comment by julianxhokaxhiu** [comment]
Allright thanks

**Comment by julianxhokaxhiu** [comment]
I was testing it here and it looks right, not as your screenshots. Have you got more than one HDR monitor attached? And is the game window running on that monitor?

**Comment by natepley** [comment]
I just have one display - an LG CX tv.  I'm on Windows 11, if that makes any difference.  The screenshots seem to be slightly exaggerated.  It doesn't look exactly that way in-game, but the posterization is definitely still there.

**Comment by julianxhokaxhiu** [comment]
This issue will be fixed when #536 will be fixed as well.

**Comment by julianxhokaxhiu** [comment]
@N8endo may I ask if you can please try on the latest canary and make sure the window is rendering on the correct monitor that has HDR?

Also, are you having more than one monitor that supports HDR? If so, move it to the screen number 1 when running the game. All the info we use to do HDR comes from the first screen that supports HDR.

**Comment by N8endo** [comment]
@julianxhokaxhiu  I just tested again.  The same issue seems to be present.  The opening FMV looked good without HDR, but HDR had really bad posterization.  I don't have multiple monitors.  Only an LG CX.

**Comment by julianxhokaxhiu** [comment]
Thanks for the feedback. I'll keep you posted on the progress.

**Comment by ChthonVII** [comment]
> Only an LG CX.

I'll bet that's the root of it. Apparently there's an issue with some LG monitors that they're missing luminance metadata, so dxgi.dll just poops out a dummy value of 799.0. See [here](https://github.com/doitsujin/dxvk/blob/master/src/dxgi/dxgi_output.cpp#L27). That's way brighter than the value that we ought to be using (the monitor's _SDR_ white level) and also, assuming [this review](https://reviewed.usatoday.com/televisions/content/lg-cx-oled-tv-series-review-picture-perfection) is correct, brighter than the LG CX's maximum output. Please try setting the max nits in FFNx.toml to 192.

**Comment by ChthonVII** [comment]
Could you please post a screen shot of what it looks like with 192 max nits? I've been working a lot on FMV issues generally and [some of the other problems in your screenshots believe I've fixed](https://github.com/julianxhokaxhiu/FFNx/issues/536#issuecomment-1477884007) (though I can't test my fixes since I lack a HDR monitor).

**Comment by julianxhokaxhiu** [comment]
@N8endo is the issue still valid? Can you please re-test on the latest canary?

**Comment by N8endo** [comment]
Ok.  I don't have the game installed, but I'll try to install and test tomorrow.

**Comment by N8endo** [comment]
@julianxhokaxhiu  @ChthonVII 
I just tested it and it seems the issue is gone!  That's wonderful!  Thank you for your hard work on this game!
Loading up the game after all this time, really makes me feel like playing the game again.  I may try another playthrough soon.

**Comment by julianxhokaxhiu** [comment]
Thanks a lot for the feedback and enjoy your playthrough :) Cheers!
