### ISSUE TITLE
[FF7] Battle swirl picture vertically stretched

### ISSUE THREAD

**Issue by Rumbah2** [julianxhokaxhiu/FFNx#67]
FFNx does stretch the picture vertically before starting the battle swirl while it does not in vanilla.

![before_swirl](https://user-images.githubusercontent.com/40009325/84436550-ebf17180-ac33-11ea-937e-7196d65e9105.png)
![swirl](https://user-images.githubusercontent.com/40009325/84436554-ec8a0800-ac33-11ea-8368-57b0605ce60e.png)

Easier to see:
http://www.framecompare.com/image-compare/screenshotcomparison/77G7GNNX

**Comment by julianxhokaxhiu** [comment]
@Rumbah2 Can you please try the latest canary? Should be fixed now. Thank you for this issue :)

**Comment by Rumbah2** [comment]
It is still wrong for me.
On Field:
http://www.framecompare.com/image-compare/screenshotcomparison/77G6WNNX
On World Map:
http://www.framecompare.com/image-compare/screenshotcomparison/99EM1NNU

**Comment by julianxhokaxhiu** [comment]
This time is fixed for good :) I did check frame by frame with RenderDoc and proportions seems to be respected now! But please double check also on your side and let me know. Canary is now building.
