### ISSUE TITLE
[FF7] Misc audio bugs with the new Audio Engine

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#91]
There have been some regressions in the new canary. From what I've tested so far I've noticed bugs in music, such as when you exit from a city to the world map the field's music lingers on for some seconds on top of the world map music before fading out. After a battle on the world map the music starts a from the beginning again (kinda like what happened in vanilla). After a battle in the world map the victory theme stays for about 3-4 seconds on top of the world map music. After the battle with Ultima Weapon in Mideel the music (weapon.ogg) ends and re-starts.

**Comment by julianxhokaxhiu** [comment]
Hi, thank you very much for the reports. You've hit a part of the code which is currently WIP and not finished. I'll keep track of this issue in order to check everything once the whole implementation will be settled :)

**Comment by eve-atum** [comment]
Not surprising... the newest canary ripped out and replaced the entire sound engine. A point of mentioning this was made on the Discord.

**Comment by julianxhokaxhiu** [comment]
I've just finished to publish another canary which improves the resume logic. Should fix the Ultima weapon track bug you mentioned.

About "cross-fading" I'm not sure how the original games handles that so I'm currently fading in and out at the same time, what is going to be stopped and what is going to be played. I'll double check how this is handled on stock experience and I'll ensure it does the same thing. What is being currently done, was my thought about cross-fading.

**Comment by daedrixxx2** [comment]
> I've just finished to publish another canary which improves the resume logic. Should fix the Ultima weapon track bug you mentioned.

Nope. Still happens. When the field music changes in cutscenes sometimes i hear like big "scratches".

> About "cross-fading" I'm not sure how the original games handles that so I'm currently fading in and out at the same time, what is going to be stopped and what is going to be played. I'll double check how this is handled on stock experience and I'll ensure it does the same thing. What is being currently done, was my thought about cross-fading.

The way it handled it before changing the sound engine sounded perfect, regarding the timings of fading in and out.
MAYBE the only improvement I think to have noticed is that inside the Lifestream with Tifa, in the black background field, every sound fx seems to be reproduced, albeit still too quietly, whereas before it reproduced them randomly.

**Comment by julianxhokaxhiu** [comment]
> Nope. Still happens. When the field music changes in cutscenes sometimes i hear like big "scratches".

Can you please share your save so I can test the scenario?

> The way it handled it before changing the sound engine sounded perfect, regarding the timings of fading in and out.
> MAYBE the only improvement I think to have noticed is that inside the Lifestream with Tifa, in the black background field, every sound fx seems to be reproduced, albeit still too quietly, whereas before it reproduced them randomly.

The fact is that how it was before maybe was not perfect as well. I'll try to have a clean game run with midis and check how it fades :)

**Comment by daedrixxx2** [comment]
[FF7PC savegames.zip](https://github.com/julianxhokaxhiu/FFNx/files/5190991/FF7PC.savegames.zip)

This is a common savegame compilation that I use to try various segments of the game. The Mideel part, before getting Cloud back is in slot7 (save06.ff7), 8th save from the bottom.

> The fact is that how it was before maybe was not perfect as well. I'll try to have a clean game run with midis and check how it fades :)

Wouldn't it be more precise to check the fading times with a psx playthrough on YT? Or on a emulator? Mednafen is maybe the most precise psx emulator there is.

**Comment by julianxhokaxhiu** [comment]
Thanks for the save file, I'll check it now.

> Wouldn't it be more precise to check the fading times with a psx playthrough on YT? Or on a emulator? Mednafen is maybe the most precise psx emulator there is.

I found out MIDI files to not fade at all. It seems though that the game engine basically provides the meaning to create our own fade effects knowning in how many steps it should fade from 127 ( max volume ) to 0. As we do use a very cool library which we just need to tell in how many seconds we need that track to fade, I've decided that 1 second is enough. This provides a really smooth transition of tracks between scenes. I'll push this change after I'll fix also the bug you found out in the  Ultima Weapon.

**Comment by daedrixxx2** [comment]
> It seems though that the game engine basically provides the meaning to create our own fade effects knowning in how many steps it should fade from 127 ( max volume ) to 0.

This is kinda how I fixed yufi.ogg not starting when recruiting Yuffie, only I added a new parameter in flevel.lpg (telling the field to start the track at 127 volume) through Makou Reactor.

**Comment by julianxhokaxhiu** [comment]
> > It seems though that the game engine basically provides the meaning to create our own fade effects knowning in how many steps it should fade from 127 ( max volume ) to 0.
> 
> This is kinda how I fixed yufi.ogg not starting when recruiting Yuffie, only I added a new parameter in flevel.lpg (telling the field to start the track at 127 volume) through Makou Reactor.

Well now it doesn't really matter as the engine itself will handle the fade out, doesn't matter the volume it is :)

Regarding the Ultima Weapon I can't really find anything strange as the music is playing out fine as expected. Maybe download the next canary ( that is building right now ) which has also the crossfade in 1s and try again. Perhaps it works better now.

**Comment by daedrixxx2** [comment]
Tried it now, this is what I found out.

The music after Ultima Weapon now continues playing without fading and restarting itself, but, for the same reason that I think fixed that issue, now the Game Over music only plays while still in battle mode, then when it fades to the Game Over screen it stops completely and there is dead silence! XD
When a track fades out during a cutscene there's still a big "scratch" sound glitch.
After a battle, the world map music re-starts itself, making it impossible to hear the full theme without stopping and waiting in the menu (original PC version bug).

> As we do use a very cool library which we just need to tell in how many seconds we need that track to fade, I've decided that 1 second is enough.

If I can say my opinion, I think that the vanilla behaviour (0 seconds) is the right one, for even in the psx version there is no fade out from a track to another.

**Comment by julianxhokaxhiu** [comment]
> Tried it now, this is what I found out.

Wow, amazing :) Thank you!

> The music after Ultima Weapon now continues playing without fading and restarting itself, but, for the same reason that I think fixed that issue, now the Game Over music only plays while still in battle mode, then when it fades to the Game Over screen it stops completely and there is dead silence! XD

For one bug that we fix, another one comes out :P We'll deal with this one too ahah

> When a track fades out during a cutscene there's still a big "scratch" sound glitch.

Yep, I can hear that too. Extremely annoying and I'm trying to find out what is going on.

> After a battle, the world map music re-starts itself, making it impossible to hear the full theme without stopping and waiting in the menu (original PC version bug).

This is a "nice-to-have" in my todo list, but I need to iron out the new Audio Engine first. But I'll definitely bring this back once that's settled :)

> If I can say my opinion, I think that the vanilla behaviour (0 seconds) is the right one, for even in the psx version there is no fade out from a track to another.

The original game when it uses MIDIs it brutally ends them, but I think that's not the right behavior. The engine does definitely ask for a crossfade and I do that only when the engine asks too. If the engine wants a hard cut, it will get that ( and that's when you hear the scratch ). So I think the 1s behavior will not hurt anyone and will provide a smooth transition anyway :)

Thank you for doing those hard tests, really appreciated. I'll ping you asap I have some more updates regarding all of the above. 
Cheers!

**Comment by daedrixxx2** [comment]
Yeah, now that you have a new sound engine, you must begin anew to know it inside and out. I understand it will take a bit of time.

Regarding the fade out, I didn't mean to have exactly 0 seconds, i.e. a hard cut, but to make it so that the two tracks don't overlap, (maybe 0.1 - 0.5 seconds?) because even with 1 second of fade it happens, it creates confusion, and it sounds bad. At least to me :P

**Comment by julianxhokaxhiu** [comment]
> Yeah, now that you have a new sound engine, you must begin anew to know it inside and out. I understand it will take a bit of time.

Thanks for the comprehension :) Anyway, some good news! I managed to fix the scratch. The core issue was on how the fade out function was handling the engine parameters. Now it is handling them like the game engine does, so audio is stopped correctly when it should, without any more scratches.

Also the game over sound is played correctly in battle and in game over screen.

Feel free to try out the next canary which is currently being built.

> Regarding the fade out, I didn't mean to have exactly 0 seconds, i.e. a hard cut, but to make it so that the two tracks don't overlap, (maybe 0.1 - 0.5 seconds?) because even with 1 second of fade it happens, it creates confusion, and it sounds bad. At least to me :P

Put them however you like but I can't delay the start of the next track while the previous is fading. So 1s should be ok to fade out the previous and start the next, should be barely unnoticeable.

**Comment by daedrixxx2** [comment]
First things first, the game over music has returned, bugged because it restarts when it gets to the game over screen, but has returned. No more scratches either, which is good :)

Now, this new sound engine, while it gets some things right, breaks things on whole new levels... Tracks that should fade out "gently" now end abruptly. Play the entire Mideel "Cloud's consciousness" segment and you'll get what I mean (after the first scene at Nibelheim's gates the music stops completely).
While the old sound engine had its own share of bugs, many of which had been patched with time, it reproduced faithfully, more or less, the vanilla behaviour of the psx game. The new one, it seems, would require setting the fade out timings one by one for every scene, because a fade out of just 1 second isn't going to be enough for every circumstance in the game.

**Comment by julianxhokaxhiu** [comment]
> First things first, the game over music has returned, bugged because it restarts when it gets to the game over screen, but has returned. No more scratches either, which is good :)

Believe it or not, that's the engine logic. If you see the logs, you'll notice the engine requires a full stop of the current track ( that is the game over ) and then it plays again the game over sound. For whatever reason. So this is a game engine issue and we may need to trial this in a different way.

> Now, this new sound engine, while it gets some things right, breaks things on whole new levels... Tracks that should fade out "gently" now end abruptly. Play the entire Mideel "Cloud's consciousness" segment and you'll get what I mean (after the first scene at Nibelheim's gates the music stops completely).

I'll need to test this.

> While the old sound engine had its own share of bugs, many of which had been patched with time, it reproduced faithfully, more or less, the vanilla behaviour of the psx game. The new one, it seems, would require setting the fade out timings one by one for every scene, because a fade out of just 1 second isn't going to be enough for every circumstance in the game.

I think we can fix this too. While fixing the fadeout I also noticed that the engine has a ton of ifs checking various things before triggering some code ( be it stop, fade out, play, etc. ) so I need to RE that part and reimplement correctly like the engine does. Only then we will have full parity. For now I'm still satisfied we do have more or less a working audio engine, but most importantly it opens the door for voice acting, which was the primary goal of this new audio engine.

We will definitely get back on track, step by step :) I'll keep this issue open as a todo, until the audio engine will be completely bug free.

**Comment by julianxhokaxhiu** [comment]
I just wanted to let you know that I've fixed the gameover restart from battle screens. Now it will continue to play it even if you transition from battle to the gameover screen :)

Additionally I've improved a little the fade out logic. Feel free to try it on top of the scenes you found out a weird behavior. It may fix those ( or not ). I'll try this personally as well later.

**Comment by daedrixxx2** [comment]
If the new sound engine can be tweaked to the full functionality and characteristics of the old one (for those who prefer a completely vanilla game, 1:1 with the psx og but remastered for 2020) then it's all good. The new features such as possibility for voice acting is a nice bonus for those interested.
In the mean time I'll be posting any new sound related bug I find here. But I encourage you to test various game segments yourself, and compare them to the psx version, so that you can know what to do first hand. Sometimes it's difficult to explain bugged behaviour just by writing :)

**Comment by daedrixxx2** [comment]
I see that with the latest canary (160) some audio fading bugs (and relative scratching) have been fixed, now the fading is closer to the original.

> If the track that would begin is the same track as before (basically there is a mini stop as the field changes location and the track ideally would continue as normal) instead the track stops completely.
Now, instead of stopping completely, the music restarts like in the former game over screen audio bug. Which shows that progress has been made :)

Would it be possible to fix the sound effects that play immediately after Tifa is in the lifestream (the field with the black background). The sfx are still played too quietly, some are played randomly and sometimes not at all.

**Comment by julianxhokaxhiu** [comment]
> Now, instead of stopping completely, the music restarts like in the former game over screen audio bug. Which shows that progress has been made :)

Thanks for the quick test. Indeed I just finished to push another patch which fixes that behavior too! I think we're getting closer to the original stock logic!

> Would it be possible to fix the sound effects that play immediately after Tifa is in the lifestream (the field with the black background). The sfx are still played too quietly, some are played randomly and sometimes not at all.

SFX replacement is a topic on its own and I'm currently focusing on Music and Voice. That will come once we settle with the new audio engine :)

**Comment by daedrixxx2** [comment]
New build .161
Entering a town, the music changes to that of the town. Exiting, and re-entering the music stays that of the world map. Tried it in Mideel.

**Comment by julianxhokaxhiu** [comment]
> New build .161
> Entering a town, the music changes to that of the town. Exiting, and re-entering the music stays that of the world map. Tried it in Mideel.

Please try the latest canary. Some more work has been done and I'm not able to reproduce this issue. Thank you!

**Comment by daedrixxx2** [comment]
I meant that the music in Mideel remained that of the world map if you exited and re-entered the village. But this has been patched in .162.

> If the track that would begin is the same track as before (basically there is a mini stop as the field changes location and the track ideally would continue as normal) instead the track stops completely.

> Now, instead of stopping completely, the music restarts like in the former game over screen audio bug.

These have been fixed as well ;) At least in the series of cutscenes I use to test the builds (should have a decent number of variations of scenes to test different behaviour).

The new option you added to the config regarding the restarting of music is cool as well.
Just one thing: During the fade-out of a FMV (i.e. Tifa and Cloud falling into the lifestream), or the fade-in of the world map music when re-entering the world map from a village (or after a battle), the music stops (or starts) too suddenly. Maybe making the music fade out lowering gradually the volume for the duration of a second at the end of the FMV as it fades to black, and gradually increasing (1 sec) the volume of the world map music after the village music ( or after the victory theme) has stopped (so the two don't overlap) would be good.

Anyway, great progress 👍

**Comment by julianxhokaxhiu** [comment]
Thanks for the feedback :) I'm really happy you are enjoying testing as well as having the flag in there. I thought it would be something useful for players, so they configure the behavior as they prefer.

Regarding the fine tuning of music transition, at the moment I'm inheriting the engine decisions, but I'll be happy to improve those aspects later on. If you didn't find anything strange after this canary I would be happy in closing this issue.

Would you be ok with this? Let me know :)

**Comment by daedrixxx2** [comment]
I've done more extensive testing. There are still numerous instances where the fading out timings should be adjusted. Some as little as 1 second, some as long as 4-5 seconds, or the music cuts too suddenly and we are left staring into a mute screen fading to black (the music should fade as the screen fades).

As for the world map music not remembering where it was after a battle or exiting a city, I think there are some instances (should be verified observing the original behaviour) where it should reset, though. Because now, even after I reset to the main menu (ctrl+r) and I load a save, the world map music continues exactly where I had left it! XD

I don't know if this issue should be considered solved, most of it has been fixed, though. If you want to close it, fine by me.

**Comment by julianxhokaxhiu** [comment]
> I've done more extensive testing. There are still numerous instances where the fading out timings should be adjusted. Some as little as 1 second, some as long as 4-5 seconds, or the music cuts too suddenly and we are left staring into a mute screen fading to black (the music should fade as the screen fades).

This issue deserves its own ticket I guess and we can better discuss this on Discord :) The issue we're using now it's all about having the Audio Engine with what was before. I think we've reached that now. Still I'm open for improvement as I said, just not right now.

> As for the world map music not remembering where it was after a battle or exiting a city, I think there are some instances (should be verified observing the original behaviour) where it should reset, though. Because now, even after I reset to the main menu (ctrl+r) and I load a save, the world map music continues exactly where I had left it! XD

Ha! Thanks for pointing this out, just pushed a patch to fix this behavior :) Feel free to try the next canary.

> I don't know if this issue should be considered solved, most of it has been fixed, though. If you want to close it, fine by me.

Allright, just let me know if the soft reset issue has been fixed and I'll proceed by closing this now if nothing else is broken. Thanks again!

**Comment by daedrixxx2** [comment]
> Allright, just let me know if the soft reset issue has been fixed and I'll proceed by closing this now if nothing else is broken. Thanks again!

Nope. The music still continues from where it left when I soft reset and then load a save (be it the same or another one from a different point in the game) O.O

> The new option you added to the config regarding the restarting of music is cool as well.

I think it might have something to do with this ^. I left it on, of course.

**Comment by daedrixxx2** [comment]
That ^ was with ver. 163. With .164 the soft reset issue has been resolved. Loading a save after a soft reset the world map music starts from the beginning as normal.
Except... I found another weird behaviour, lol. A bug behind a fixed bug. Basically if I get a game over screen and I load a save, the world map music resumes from where it left off before the battle in which I died. If I die again, or I soft reset, the next game over screen will be silent, no music. When I load the game again everything fixes itself though, and I'll have to die again to re-trigger the bug.

**Comment by julianxhokaxhiu** [comment]
> Except... I found another weird behaviour, lol. A bug behind a fixed bug. Basically if I get a game over screen and I load a save, the world map music resumes from where it left off before the battle in which I died. If I die again, or I soft reset, the next game over screen will be silent, no music. When I load the game again everything fixes itself though, and I'll have to die again to re-trigger the bug.

Thanks for the feedback. I forgot about the "normal possible scenario" of a gameover, so I've ironed the code to trigger the audio engine flush as soon as the gameover sound is being played ( which means that you've reached the gameover screen ).

Doesn't matter how you land there ( lost a fight or you wanted a soft reset ), the audio engine will be flushed and will restart exactly like you would have closed and opened the game :) The canary is currently building. Let me know how it goes.

**Comment by daedrixxx2** [comment]
>  I forgot about the "normal possible scenario" of a gameover, so I've ironed the code to trigger the audio engine flush as soon as the gameover sound is being played ( which means that you've reached the gameover screen ).

After more testing, I can confirm that now the world map music restarts correctly after any kind of game over 👍 
On some occasions, after a soft reset, the game over screen has no music. Maybe understandable, as this occurrence was not meant to be triggered by default by the engine. This happens randomly, and only when triggered by a soft reset.

Another thing that happened (unrelated) when summoning was that as the character faded to begin the summon animation the music stopped for half a second (maybe loading related?) then continued normally.

Well then, good progress has been made and we're getting ever closer to the original sound engine. Apart from these little imperfections i mentioned above, I would consider this issue resolved.

**Comment by julianxhokaxhiu** [comment]
Thank you, this feedback is really appreciated :) We can of course trial single cases in dedicated tickets. Time to move on with the Voice over implementation!

Looking forward in talking with you again on Discord. Feel free to join over there!
